# Generated by Django 5.0.6 on 2024-07-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_imageshare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageShare',
        ),
    ]
